apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-prometheus-stack

commonLabels:
  environment: staging
  managed-by: fluxcd
  app.kubernetes.io/part-of: monitoring
  layer: monitoring-controllers-staging
