# Deployment for Bookmark-App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-app-deploy
  labels:
    app.kubernetes.io/name: bookmark-app
    app.kubernetes.io/component: backend
    owner: iammanjubhandari
    org: iammanjubhandari-org
    environment: base

spec:
  replicas: 1
  revisionHistoryLimit: 3               # 3 old ReplicaSets kept for rollback
  strategy:
    type: RollingUpdate                 # Rolling updates
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

selector:
    matchLabels:
      app: bookmark-app

template:
  metadata:
    labels:
      app: bookmark-app

containers:
  - name: bookmark-app
    image: sissbruecker/linkding:1.31.0
    imagePullPolicy: IfNotPresent


ports:
  - containerPort: 9090

envFrom:
  - secretRef:
      name: linkding-container-env

volumeMounts:
  - name: bookmark-data
    mountPath: /etc/bookmark/data



    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

volumes:
    - name: bookmark-data
      persistentVolumeClaim:
        claimName: bookmark-data-pvc