# PersistentVolumeClaim for Bookmark-App data

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookmark-app-pvc
  lables:
    app.kubernetes.io/name: bookmark-app
    app.kubernetes.io/component: storage
    owner: iammanjubhandari
    org: iammanjubhandari-org
    environment: base
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn



