apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  labels:
    app: linkding



spec:
  replicas: 1
  revisionHistoryLimit: 3               # 3 old ReplicaSets kept for rollback
  strategy:
    type: RollingUpdate                 # Rolling updates
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

selector:
    matchLabels:
      app: linkding

template:
  metadata:
    labels:
      app: linkding

containers:
  - name: linkding
    image: sissbruecker/linkding:1.31.0
    imagePullPolicy: IfNotPresent


ports:
  - containerPort: 9090

envFrom:
  - secretRef:
      name: linkding-container-env

volumeMounts:
  - name: linkding-data
    mountPath: /etc/linkding/data



    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

volumes:
    - name: linkding-data
      persistentVolumeClaim:
        claimName: linkding-data-pvc